### 실습물 제출 가이드라인
- 아래에 주어진 코드들을 실행해서 python의 동작 원리를 이해하시오. 그리고, # M 으로 주어진 부분은 코드를 작성하고 실행하시오.
- 주어진 코드들을 다 실행해 보고 결과를 확인하면 3점을 부여합니다.
- "# M"으로 주어진 문제는 정확한 답을 작성하면 표기된 점수가 부여됩니다.

## numpy

In [3]:
# import는 노트북 실행 중 한 번만 하면 충분함
import numpy as np

#### array 만들기

In [2]:
# 1
arr1d = np.array([1, 2, 3, 4, 5]) # 1차원 배열 생성
print(arr1d)
print(arr1d.shape)

[1 2 3 4 5]
(5,)


In [3]:
# 2
arr1d = np.array(range(1,6)) # 1차원 배열 생성
print(arr1d)
print(arr1d.shape)

[1 2 3 4 5]
(5,)


In [4]:
# 3
arr2d = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 10]]) # 2차원 배열 생성
print(arr2d)
print(arr2d.shape)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]
(3, 4)


In [5]:
# 4
arr2d = np.array((range(1,5), range(4,8), range(7,11))) # 2차원 배열 생성
print(arr2d)
print(arr2d.shape) 

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]
(3, 4)


In [6]:
# 5
# 단일 item의 경우, 0차원 array 생성
# indexing이 불가한 set, dictionary
# 숫자 하나, string 하나 등

arr = np.array({1:2, 3:4})
print(arr)
print(arr.shape)           
print(type(arr))

{1: 2, 3: 4}
()
<class 'numpy.ndarray'>


In [7]:
# 6
arr = np.array("hello")
print(arr)
print(arr.shape)           
print(type(arr))

hello
()
<class 'numpy.ndarray'>


In [10]:
# M1
# 5 5 5 5 5
# 6 6 6 6 6 
# 7 7 7 7 7
# 위와 같은 3x5 2차원 array를 만드시오. (0.2점)
arr = np.array([
    [5, 5, 5, 5, 5],
    [6, 6, 6, 6, 6],
    [7, 7, 7, 7, 7]
])
print(arr)

[[5 5 5 5 5]
 [6 6 6 6 6]
 [7 7 7 7 7]]


In [11]:
# 7
zeros = np.zeros(10)  # 0.0 10개로 구성된 1차원 arrary 
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [12]:
# 8
ones = np.ones(10)    # 1.0 10개로 구성된 1차원 arrary 
print(ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [13]:
# 9
twos = ones * 2        # 2.0 10개로 구성된 1차원 arrary, ones의 각 요소에 2배한 값으로 twos 생성
print(twos)

[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]


In [15]:
# M2 
# 8이 15개인 array를 만드시오.  (0.1점)
eights = np.ones(15) * 8
print(eights)

[8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]


In [16]:
# 10
# 0부터 9까지의 숫자 배열 생성
arr1 = np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
# 11
# 5부터 19까지의 숫자 배열 생성 (간격은 2)
arr2 = np.arange(5, 20, 2)
print(arr2)

[ 5  7  9 11 13 15 17 19]


In [18]:
# 12
# 0부터 2 * pi까지의 간격이 0.1인 각도 배열 생성
angles = np.arange(0, 2 * np.pi, 0.1)
print(angles)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3
 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2]


In [21]:
# M3
# 1에서 30 사이의 4의 배수로 이루어진 배열을 np.arange()를
# 사용하여 만드시오. (0.1점)
myarr = np.arange(4, 31, 4)
print(myarr)

[ 4  8 12 16 20 24 28]


In [22]:
# 13
# 0과 1 사이의 난수 다섯 개로 초기화된 1차원 배열 생성
random_array_1d = np.random.random(5)
print(random_array_1d)

[0.80033044 0.86555156 0.2078127  0.89630319 0.98825436]


In [23]:
# 14
# 0에서 1 사이의 난수로 2개의 행, 3개의 열을 갖는 배열 생성
random_floats = np.random.rand(2, 3)
print(random_floats)

[[0.18209199 0.69898092 0.90187138]
 [0.0107556  0.36901688 0.37621269]]


In [24]:
# 15
# 평균=0, 분산=1인 정규 분포를 따르는 난수로 초기화된 1차원 배열 생성
random_normals = np.random.randn(6)   
print(random_normals)

[ 0.52663178 -0.44550023 -0.39839091 -0.69668994 -1.95617737  0.43311085]


In [25]:
# 16
# 특정 범위 내의 정수로 초기화된 1차원 배열 생성
# 1 이상 10 이하 정수 난수로 크기 5의 배열 
random_integer_array = np.random.randint(1, 11, size=5)  
print(random_integer_array)

[4 3 8 5 4]


In [26]:
# 17
# 정규 분포를 따르는 난수로 초기화된 2차원 배열 생성
mean, std_dev = 0, 1
random_normal_array = np.random.normal(mean, std_dev, size=(3, 3)) # 3x3 크기의 난수 배열
print(random_normal_array)

[[-0.71896903  0.76791668 -1.21860129]
 [-0.06126696  1.28607125  2.49345327]
 [-0.87252196 -0.35361529  1.55824544]]


In [29]:
# M4
# 30 이하의 양수 난수로 이루어진 크기가 10인 1차원 배열을 만드시오. (0.1점)
ran_arr = np.random.randint(0, 30, 10)
print(ran_arr)

[12 15 15 26 23  1 20 21  7 27]


In [30]:
# 18
# 0 또는 1을 무작위로 선택하여 초기화된 1차원 배열 생성
random_choice_array = np.random.choice([0, 1], size=5)
print(random_choice_array)

[0 1 0 1 0]


In [33]:
# 19
# list 내에서 임의로 선택
# 중복을 허용하는 경우, 허용하지 않는 경우
choices = np.random.choice([2, 4, 6, 8, 10], size=3, replace=False)
print(choices); print("-"*10)
choices_dup = np.random.choice([2, 4, 6, 8, 10], size=3)  
print(choices_dup)

[4 8 2]
----------
[6 8 6]


In [34]:
# 20
# 중복을 허용하지 않는 경우
candidates = ['apple', 'cherry', 'melon', 'pear', 'peach', 'lime', 'lemon']
fruits = np.random.choice(candidates, size=3, replace=False)
print(fruits)

['lime' 'cherry' 'pear']


In [36]:
# 21
# 각 item의 선택 확률 지정 가능
candidates = ['apple', 'cherry', 'melon', 'pear', 'peach', 'lime', 'lemon']
probabilities = [0.4, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
fruits_dup=np.random.choice(candidates, size=3, p=probabilities)
print(fruits_dup)

['peach' 'apple' 'apple']


In [40]:
# M5
# fruits=['peach', 'apple', 'pear', 'banana', 'coconut', 'kiwi']로 주어졌을 때,
# 무작위로 3개의 과일명을 선택하여 1차원 배열을 만드시오. (0.2점)
fruits=['peach', 'apple', 'pear', 'banana', 'coconut', 'kiwi']
fruits_dup2 = np.random.choice(fruits, size = 3)
print(fruits_dup2)

['peach' 'pear' 'banana']


In [41]:
# 22
array1 = np.arange(10)
print(array1)
print('---')
print(array1.reshape(2,5))

[0 1 2 3 4 5 6 7 8 9]
---
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [42]:
# 23
zeros_3d = np.zeros(27).reshape(3,3,3)  # 27개의 0으로 array를 만든 후 3x3x3 행렬로 변경
print(zeros_3d)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [43]:
# M6
# 16개의 1로 array를 만들고, 4x4 2차원 array로 변경하시오. (0.1점)
one_arr = np.ones(16)
print(one_arr)
two_arr = one_arr.reshape(4, 4)
print(two_arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [44]:
# 24 
# 1차원 array에 요소 추가
array1 = np.array([1,2,3])
array2 = np.append(array1, [7,8])

print(array2)

[1 2 3 7 8]


In [45]:
# 25
# 2차원 array에 요소 추가 
array1 = np.array([[1,2,3],[4,5,6]])
array2 = np.append(array1, [[7,8,9], [10, 11, 12]])

print(array2)  # 1차원 array로 해체됨

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [46]:
# 26
# 2차원 array에 행 추가 
array1 = np.array([[1,2,3],[4,5,6]])
array2 = np.append(array1, [[7,8,9], [10, 11,12]], axis=0) 

print(array2)  

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [47]:
# 27
# 2차원 array에 열 추가 
array1 = np.array([[1,2,3],[4,5,6]])
array2 = np.append(array1, [[7,8],[9,10]], axis=1) 

print(array2)  

[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


#### indexing, slicing

In [48]:
# 28
# row 중심
data = np.array([['a', 'b', 'c'],['d', 'e', 'f'], ['g', 'h', 'i']])
print(data[1])

['d' 'e' 'f']


In [49]:
# 29
data = np.array([['a', 'b', 'c'],['d', 'e', 'f'], ['g', 'h', 'i']])

print(data[1][2])
print(data[1,2])

f
f


In [50]:
# 30
data = np.array([['a', 'b', 'c'],['d', 'e', 'f'], ['g', 'h', 'i']])

print(data[2][1:]) 

['h' 'i']


In [51]:
# 31
data = np.array([['a', 'b', 'c'],['d', 'e', 'f'], ['g', 'h', 'i']])

print(data[1:][1])   

['g' 'h' 'i']


In [52]:
# 32
data = np.array([['a', 'b', 'c'],['d', 'e', 'f'], ['g', 'h', 'i']])

print(data[1:][0][1])  # ((data[1:])[0])[1] 과 동일

e


In [53]:
# 33
data = np.array([['a', 'b', 'c'],['d', 'e', 'f'], ['g', 'h', 'i']])

print(data[-2:])     

[['d' 'e' 'f']
 ['g' 'h' 'i']]


In [54]:
# 34
# column 중심
data = np.array([['a', 'b', 'c'],['d', 'e', 'f'], ['g', 'h', 'i']])

print(data[:, 1]) # index 1번 열 전체 읽기

['b' 'e' 'h']


In [55]:
# 35
data = np.array([['a', 'b', 'c'],['d', 'e', 'f'], ['g', 'h', 'i']])

print((data[:, 1])[2]) # index 1번 열 중 index 2번 item

h


In [56]:
# 36
data = np.array([['a', 'b', 'c'],['d', 'e', 'f'], ['g', 'h', 'i']])

print(data[:, -2:][2]) # data의 마지막 두 열로 구성된 행렬의 세번째 행

['h' 'i']


In [57]:
# 37
data = np.array([['a', 'b', 'c'],['d', 'e', 'f'], ['g', 'h', 'i']])

print(data[1:, 1:]) # index 1번 행부터, index 1번 열부터  

[['e' 'f']
 ['h' 'i']]


In [58]:
# 38
data = np.array([['a', 'b', 'c'],['d', 'e', 'f'], ['g', 'h', 'i']])

print(data[1:, [1]])

[['e']
 ['h']]


In [71]:
# M7
# colors = ["red", "blue", "green", "yellow", "purple", "orange", "black", "white", "pink"]
# 위의 list를 3x3 2차원 배열 colors_arr로 변환하시오 (0.2점)
# 'yellow'를 출력하기 위한 indexing, slicing 방법을 3가지 제시하시오. (0.3점)
# print()를 사용하여 맞는 방법임을 확인하시오.
colors = np.array(["red", "blue", "green", "yellow", "purple",\
          "orange", "black", "white", "pink"])
colors_arr = colors.reshape(3, 3)
print(colors_arr)

print(colors_arr[1, 0])
print(colors_arr[1][0])
print(colors_arr[1:][0][0])


[['red' 'blue' 'green']
 ['yellow' 'purple' 'orange']
 ['black' 'white' 'pink']]
yellow
yellow
yellow


In [77]:
# M8
# M6에서 만들어진 colors_arr으로부터 ['purple' 'white'] 출력을 얻을 수 있는 
# slicing 방법을 3가지 제시하시오. (0.6점)
# print()를 사용하여 맞는 방법임을 확안하시오.

print(colors_arr[1:, 1])
print(colors_arr.T[1, 1:])
print(colors_arr[1:][:, 1])

['purple' 'white']
['purple' 'white']
['purple' 'white']


#### operation

In [78]:
# 39
arr1d = np.array([1, 2, 3, 4, 5]) # 1차원 배열 생성
arr2d = np.array([[1, 2, 3], [4, 5, 6]]) # 2차원 배열 생성

# 각 원소에 2를 더하기
arr1d_plus_two = arr1d + 2
print(arr1d_plus_two)

arr2d_plus_two = arr2d + 2
print(arr2d_plus_two)

[3 4 5 6 7]
[[3 4 5]
 [6 7 8]]


In [ ]:
# 40
arr1d = np.array([1, 2, 3, 4, 5]) # 1차원 배열 생성
arr2d = np.array([[1, 2, 3], [4, 5, 6]]) # 2차원 배열 생성

# 각 원소에 3을 곱하기
arr1d_times_three = arr1d * 3
print(arr1d_times_three)

arr2d_times_three = arr2d * 3
print(arr2d_times_three)

In [ ]:
# 41
arr1d = np.array([1, 2, 3, 4, 5]) # 1차원 배열 생성
arr2d = np.array([[1, 2, 3], [4, 5, 6]]) # 2차원 배열 생성

# 각 원소 제곱
arr1d_squared = arr1d ** 2
print(arr1d_squared)

arr2d_squared = arr2d ** 2
print(arr2d_squared)

In [79]:
# 42
arr = np.array([[1, 2, 3], [4, 5, 6]])  

print("mean =", arr.mean())
print("max =", arr.max())
print("min =", arr.min())
print("sum =", arr.sum())
print("std dev =", arr.std())

mean = 3.5
max = 6
min = 1
sum = 21
std dev = 1.707825127659933


In [102]:
# M9 (0.8점)
# 임의의 데이터 만들기
# 사용자 20명의 키 데이터를 m 단위로  1.5 이상 1.9 미만 임의의 값으로 생성 : user_heights (0.2점)
# 사용자 20명의 몸무게 데이터를 50 이상 90 미만 임의의 값으로 생성 : user_weights (0.2점)
# dictionary의 10, 11, 18번 코드를 참고하여,
# user_heights와 user_weights를 사용해서 각 사용자의 BMI를 저장 : user_bmi
# user_bmi가 25이상이면 'fat', 23과 25 사이면 'over', 18.5와 23 사이면 'normal', 
# 18.5 미만이면 'under'로 판정하여 user_evaluation이라는 list를 만들기 (0.4점)
# 사용자의 BMI는 소수 둘째자리까지만 저장한다
# 실행 사례)
# [('고객1', 23.58, 'over'), ('고객2', 29.28, 'fat'), ('고객3', 28.02, 'fat'), ('고객4', 24.64, 'over'), ('고객5', 21.81, 'normal'), ('고객6', 19.87, 'normal'), ('고객7', 16.41, 'under'), ('고객8', 22.75, 'normal'), ('고객9', 28.88, 'fat'), ('고객10', 25.17, 'fat')]

user_heights = np.random.uniform(1.5, 1.9, 20)
user_weights = np.random.uniform(50, 90, 20)
print(user_heights)
print(user_weights)
user_bmi = np.round(user_weights / (user_heights ** 2), 2)
print(user_bmi)
user_evaluation = []
index = 1
for bmi in user_bmi:
    if bmi >= 25:
        evaluation = 'fat'
    elif bmi >= 23:
        evaluation = 'over'
    elif bmi >= 18.5:
        evaluation = 'normal'
    else: 
        evaluation = 'under'
    user_evaluation.append((f'고객{index}', bmi, evaluation))
    index += 1
print(user_evaluation)

[1.72558455 1.62088446 1.78624786 1.62439184 1.62804391 1.70104261
 1.79264215 1.61707367 1.75855267 1.61366058 1.87681918 1.53430807
 1.81257252 1.82298265 1.52339975 1.57950382 1.69591296 1.61844958
 1.59779438 1.63794986]
[65.01860756 57.17726933 74.96635637 68.91310445 69.74485636 87.82520305
 61.21761859 57.65406    57.84899015 63.5170102  61.17529059 86.32488605
 52.34883533 52.95993433 73.30730058 87.73023364 62.44358619 72.61956964
 62.88310615 64.72144462]
[21.84 21.76 23.5  26.12 26.31 30.35 19.05 22.05 18.71 24.39 17.37 36.67
 15.93 15.94 31.59 35.16 21.71 27.72 24.63 24.12]
[('고객1', 21.84, 'normal'), ('고객2', 21.76, 'normal'), ('고객3', 23.5, 'over'), ('고객4', 26.12, 'fat'), ('고객5', 26.31, 'fat'), ('고객6', 30.35, 'fat'), ('고객7', 19.05, 'normal'), ('고객8', 22.05, 'normal'), ('고객9', 18.71, 'normal'), ('고객10', 24.39, 'over'), ('고객11', 17.37, 'under'), ('고객12', 36.67, 'fat'), ('고객13', 15.93, 'under'), ('고객14', 15.94, 'under'), ('고객15', 31.59, 'fat'), ('고객16', 35.16, 'fat'), ('고객17', 

In [103]:
# 43
# array 간 연산
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print('A is\n', A)
print('B is\n', B)

A is
 [[1 2]
 [3 4]]
B is
 [[5 6]
 [7 8]]


In [104]:
# 44
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C = A + B     # 대응하는 요소들 간의 합
print("sum\n", C, '\n')

sum
 [[ 6  8]
 [10 12]] 



In [107]:
# 45
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

E = A * B     # 대응하는 elemenet들 간의 곱
print("element-wise product\n", E, '\n')

element-wise product
 [[ 5 12]
 [21 32]] 



In [105]:
# 46
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

F = A @ B     # 내적, E=np.dot(A, B) 또는 E = A.dot(B)
print("product\n", F, '\n')

product
 [[19 22]
 [43 50]] 



In [106]:
# 47
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

G = A | B     # 대응하는 요소들 간의 bitwise OR
print("bitwise OR \n", G, '\n')

bitwise OR 
 [[ 5  6]
 [ 7 12]] 



In [108]:
# 48
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

H = A > B     # 대응하는 요소들 간의 크기 비교
print("larger than \n", H, '\n')

larger than 
 [[False False]
 [False False]] 



In [109]:
### 참고
# numeric data에 대해서만 적용 가능
strings = np.array([['1'], ['2'], ['3']])
strings2 = np.array(['1', '2', '3'])
print(strings+['1'])  # 오류
print(strings2+'a')   # 오류 

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U1'), dtype('<U1')) -> None

In [115]:
# M10
# 0에서 20 사이의 정수(20 미포함) 중에서 임의로 16개의 정수를 만들어서(중복 허용), 
# 4x4 2차원 배열 rand_arr을 만들어 출력하고 (0.3점)
# 이 배열의 각 원소를 2배하고 다시 1을 더한 값을 가진 rand_arr2를 만드는 코드를 작성하시오 (0.2점)
# 결과를 확인할 수 있도록 출력하시오.
nand_arr = np.random.randint(0, 20, 16).reshape(4, 4)
print(nand_arr)

rand_arr2 = nand_arr * 2 + 1
print(rand_arr2)

[[ 3  8  3 19]
 [17 17  4 13]
 [ 1 16 19  1]
 [13 19 14 19]]
[[ 7 17  7 39]
 [35 35  9 27]
 [ 3 33 39  3]
 [27 39 29 39]]


In [6]:
# 49
sample_array = np.array([4, 3, 7, 2, 5, 6])
lower, upper = 3, 7

# lower보다 큰 원소 찾기
bt_cond = sample_array > lower
print(bt_cond)
print(f"items larger than {lower}:", sample_array[bt_cond])

[ True False  True False  True  True]
items larger than 3: [4 7 5 6]


In [7]:
# 50
sample_array = np.array([4, 3, 7, 2, 5, 6])
lower, upper = 3, 7
# upper보다 작은 원소 찾기
st_cond = sample_array < upper
print(st_cond)
print(f"items smaller than {upper}:", sample_array[st_cond])

[ True  True False  True  True  True]
items smaller than 7: [4 3 2 5 6]


In [8]:
# 51
sample_array = np.array([4, 3, 7, 2, 5, 6])
lower, upper = 3, 7
# 조건 결합: lower보다 크고 upper보다 작은 요소들 선택
combined_cond = bt_cond & st_cond
print(f"Condition ((array > {lower}) & (array < {upper})):", combined_cond)
filtered_array = sample_array[combined_cond]
print(f"items between {lower} and {upper}:", filtered_array)

Condition ((array > 3) & (array < 7)): [ True False False False  True  True]
items between 3 and 7: [4 5 6]


In [9]:
# 52
# boolean indexing

# 배열 생성
array_one = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
array_two = np.array([3, 2, 5, 4, 7, 6, 1, 8, 10, 9])

# 조건: array1 중 array2보다 큰 값
condition = (array_one > array_two) # array내 각 요소들에 대해 크기를 비교한 결과를 condition에 모음
print("Condition (array_one > array_two):", condition)

# Boolean indexing을 사용하여 조건을 만족하는 요소들 선택
count_filtered_items = len(array_one[condition])
print("Number of items (array_one > array_two):", filtered_array)

Condition (array_one > array_two): [False False False False False False  True False False  True]
Number of items (array_one > array_two): [4 5 6]


In [10]:
# 53
# 색깔 목록에서 잉크의 색을 랜덤하게 선택하고, 색깔별 잉크의 수를 출력
colors = ["red", "blue", "green", "yellow", "purple", "orange", "black", 
          "white", "pink"]
n_of_inks = 7
inks = np.random.choice(colors, n_of_inks)

color_counts = [len(inks[inks==item]) for item in colors]
for name, count in zip(colors, color_counts):
  print(name,":", count, end="  ")

red : 0  blue : 1  green : 1  yellow : 1  purple : 1  orange : 3  black : 0  white : 0  pink : 0  

In [ ]:
# 54
# 수강 목록에 'math'가 포함된 학생의 수강과목 확인

students = np.array([['english', 'korean', 'history'], 
                     ['korean', 'math', 'physics'],
                     ['english', 'physics', 'math']])

# 각 요소에 대해 'math'와의 일치 여부 확인
filter_matrix = students == 'math'
print(filter_matrix)

# 행 기준으로 하나라도 True가 있는 경우, True
condition = np.any(filter_matrix, axis=1)
print(condition)

result = students[condition]
# result = students[np.any(students == 'math', axis=1)]
print(result)

In [ ]:
## numpy 활용 사례
## 주사위를 10번 던져서 나온 결과의 평균을 구하는 실험을 10000번 반복

import numpy as np
means = [np.mean(np.random.randint(1, 7, 10)) for _ in range(10000)]

## 평균의 분포 시각화
import matplotlib.pyplot as plt
plt.hist(means, bins=50, density=True)
plt.show()

In [ ]:
## numpy 활용 사례
## 주사위를 10번 던져서 나온 결과의 분산을 구하는 실험을 10000번 반복

import numpy as np
variances = [np.var(np.random.randint(1, 7, 10)) for _ in range(10000)]

## 분산의 분포 시각화
plt.hist(variances, bins=50, density=True)
plt.show()