### 실습물 제출 가이드라인
- 아래에 주어진 코드들을 실행해서 python의 동작 원리를 이해하시오. 그리고, # M 으로 주어진 부분은 코드를 작성하고 실행하시오.
- 주어진 코드들을 다 실행해 보고 결과를 확인하면 3점을 부여합니다.
- "# M"으로 주어진 문제는 정확한 답을 작성하면 표기된 점수가 부여됩니다.

## Pandas data frame

In [22]:
import pandas as pd
import numpy as np

In [23]:
# pandas DataFrame을 사용하지 않고 처리하기
# 사용자로부터 주어진 data
quiz1 = [('kim', 2), ('kang', 2), ('lee', 3), ('cho', 4), ('han', 5)]
quiz2 = [('kim', 2), ('kang', 3), ('lee', 2), ('cho', 5), ('han', 2)]
quiz3 = [('kim', 3), ('kang', 4), ('lee', 3), ('cho', 4), ('han', 3)]
quiz4 = [('kim', 4), ('kang', 3), ('lee', 4), ('cho', 4), ('han', 2)]
weights = [0.2, 0.3, 0.4, 0.1]

# 사용자의 data 처리하기
quiz_list = [quiz1, quiz2, quiz3, quiz4]
n_of_students = len(quiz1)
n_of_quizes = len(quiz_list)
names = [key for key, value in quiz1]

# weight를 부여서 각 학생의 점수 총합 정리한 list 만들기
sum_list = []; avg_list = []
for i in range(n_of_students):
    total = 0
    for j in range(n_of_quizes):
        total += quiz_list[j][i][1]*weights[j]
    sum_list.append((names[i], total))
print(sum_list)

# list comprehension version
# sum_list = [(quiz1[i][0], sum(quiz[i][1]*weights[idx] for idx, quiz in enumerate(quiz_list))) for i in range(n_of_students)]
# print(sum_list)

# 각 quiz들에 대해 점수 두 배로 올리기
for i in range(n_of_quizes):
    quiz_list[i] = [(name, score*2) for name, score in quiz_list[i]]
    print(quiz_list[i])

[('kim', 2.6), ('kang', 3.2), ('lee', 2.8000000000000003), ('cho', 4.3), ('han', 3.0000000000000004)]
[('kim', 4), ('kang', 4), ('lee', 6), ('cho', 8), ('han', 10)]
[('kim', 4), ('kang', 6), ('lee', 4), ('cho', 10), ('han', 4)]
[('kim', 6), ('kang', 8), ('lee', 6), ('cho', 8), ('han', 6)]
[('kim', 8), ('kang', 6), ('lee', 8), ('cho', 8), ('han', 4)]


In [24]:
# pandas를 사용해서 처리하기

# 사용자로부터 주어진 data
quiz1 = [('kim', 2), ('kang', 2), ('lee', 3), ('cho', 4), ('han', 5)]
quiz2 = [('kim', 2), ('kang', 3), ('lee', 2), ('cho', 5), ('han', 2)]
quiz3 = [('kim', 3), ('kang', 4), ('lee', 3), ('cho', 4), ('han', 3)]
quiz4 = [('kim', 4), ('kang', 3), ('lee', 4), ('cho', 4), ('han', 2)]
weights = [0.2, 0.3, 0.4, 0.1]

# 사용자의 data 처리하기
user_scores = {'quiz1':[item[1] for item in quiz1], 
               'quiz2':[item[1] for item in quiz2],  
               'quiz3':[item[1] for item in quiz3], 
               'quiz4':[item[1] for item in quiz3]}
names = [item[0] for item in quiz1]

# data frame 만들기
df = pd.DataFrame(user_scores, index=names)

print(df)
# weight를 부여서 각 학생의 점수 총합 정리한 column추가
df['total'] = df.dot(weights)

# 각 quiz의 점수 2배로 올리기
df = df*2
print(df)
print(df['quiz3'][1])

      quiz1  quiz2  quiz3  quiz4
kim       2      2      3      3
kang      2      3      4      4
lee       3      2      3      3
cho       4      5      4      4
han       5      2      3      3
      quiz1  quiz2  quiz3  quiz4  total
kim       4      4      6      6    5.0
kang      4      6      8      8    6.6
lee       6      4      6      6    5.4
cho       8     10      8      8    8.6
han      10      4      6      6    6.2
8


/tmp/ipykernel_1190/2644070495.py:27: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(df['quiz3'][1])


#### DataFrame 만들기

In [25]:
# 노트북 실행 중 한 번 실행하면 충분
import pandas as pd
import numpy as np

In [26]:
# 1
df = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(df)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9


In [27]:
# 2
df = pd.DataFrame(data=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), 
                  index=[2.5, 12.6, 4.8], columns=[48, 49, 50])
print(df)

      48  49  50
2.5    1   2   3
12.6   4   5   6
4.8    7   8   9


In [28]:
# 3
# row 중심 DataFrame 생성
data_list = [['Alice', 25, 'Female'],  ['Bob', 30, 'Male'], ['Charlie', 22, 'Male']]
columns = ['Name', 'Age', 'Gender']
df1 = pd.DataFrame(data_list, columns=columns)
print(df1)

      Name  Age  Gender
0    Alice   25  Female
1      Bob   30    Male
2  Charlie   22    Male


In [29]:
# 4
# column 중심  DataFrame 생성
data_dict = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 22],
    'Gender': ['Female', 'Male', 'Male']} 

df2 = pd.DataFrame(data_dict)
print(df2)

      Name  Age  Gender
0    Alice   25  Female
1      Bob   30    Male
2  Charlie   22    Male


#### indexing, slicing

In [30]:
# 6
# DataFrame에 []를 사용해서 indexing, slicing 적용하기: 값 읽어내기, 바꾸기
#
# df[column label][index]
# df[column label]
# df[[column label1, column label2]]
# df[row index1:row index2:step]

base_info={'midterm':[80, 70, 65, 75], 'homework':[25, 20, 27, 23],
          'final':[75, 80, 70, 80], 'report':[35, 30, 32, 27]}
index_list=['202311111', '202322222', '202333333', '202344444']
df_course=pd.DataFrame(base_info, index=index_list)

In [31]:
# 6-1 특정 열 읽어내기
print(df_course['midterm'])  # Series

202311111    80
202322222    70
202333333    65
202344444    75
Name: midterm, dtype: int64


In [32]:
# 6-2
print(df_course['midterm']['202333333']) # integer

65


In [33]:
# 6-3
print(df_course['midterm'][2]) # integer

65


/tmp/ipykernel_1190/3922793187.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(df_course['midterm'][2]) # integer


In [34]:
# 6-4
print(df_course[['midterm','report']])  # DataFrame

           midterm  report
202311111       80      35
202322222       70      30
202333333       65      32
202344444       75      27


In [35]:
# 6-5
print(df_course[1:3])  # DataFrame

           midterm  homework  final  report
202322222       70        20     80      30
202333333       65        27     70      32


In [36]:
# 6-6
print(df_course[1:3:2])  # DataFrame

           midterm  homework  final  report
202322222       70        20     80      30


In [37]:
# 6-7
# 값 바꾸기
df_course['midterm'] = 90
print(df_course)

           midterm  homework  final  report
202311111       90        25     75      35
202322222       90        20     80      30
202333333       90        27     70      32
202344444       90        23     80      27


In [38]:
# 6-8
# 구간을 동일한 값으로 변경하기
df_course['202311111':'202333333'] = 90 
print(df_course)

           midterm  homework  final  report
202311111       90        90     90      90
202322222       90        90     90      90
202333333       90        90     90      90
202344444       90        23     80      27


In [39]:
# 6-9
# DataFrame 생성 단계에 없었던 column 생성 가능 (맨 끝에 추가)
df_course['univeristy'] = 'Ajou'
print(df_course)

           midterm  homework  final  report univeristy
202311111       90        90     90      90       Ajou
202322222       90        90     90      90       Ajou
202333333       90        90     90      90       Ajou
202344444       90        23     80      27       Ajou


In [40]:
# 6-10
# column을 결합하여 새로운 column 생성 가능
df_course['test'] = df_course['midterm'] *0.5 + df_course['final']*0.5
print(df_course)

           midterm  homework  final  report univeristy  test
202311111       90        90     90      90       Ajou  90.0
202322222       90        90     90      90       Ajou  90.0
202333333       90        90     90      90       Ajou  90.0
202344444       90        23     80      27       Ajou  85.0


In [41]:
# 7
# loc을 사용하여 indexing과 slicing : 값 읽기, 바꾸기
#
# df.loc[index label, column label]
# df.loc[index label]
# df.loc[index label][column label]
# df.loc[index label1:index label2:step, column label1:column label2:step]
# df.loc[index label list][column label list]

base_info={'midterm':[80, 70, 65, 75], 'homework':[25, 20, 27, 23],
          'final':[75, 80, 70, 80], 'report':[35, 30, 32, 27]}
index_list=['202311111', '202322222', '202333333', '202344444']
df_course=pd.DataFrame(base_info, index=index_list)
print(df_course)
print(df_course[1:3])

           midterm  homework  final  report
202311111       80        25     75      35
202322222       70        20     80      30
202333333       65        27     70      32
202344444       75        23     80      27
           midterm  homework  final  report
202322222       70        20     80      30
202333333       65        27     70      32


In [42]:
# 7-1
# loc을 사용하여 indexing과 slicing : 값 읽기, 바꾸기
print(df_course.loc['202344444', 'midterm'])

75


In [43]:
# 7-2
# loc을 사용하여 indexing과 slicing : 값 읽기, 바꾸기
print(df_course.loc['202344444']) # Series

midterm     75
homework    23
final       80
report      27
Name: 202344444, dtype: int64


In [44]:
# 7-3
# loc을 사용하여 indexing과 slicing : 값 읽기, 바꾸기
print(df_course.loc['202311111':'202344444':2]) 

           midterm  homework  final  report
202311111       80        25     75      35
202333333       65        27     70      32


In [45]:
# 7-4
# loc을 사용하여 indexing과 slicing : 값 읽기, 바꾸기
print(df_course.loc[['202311111','202344444']]) 

           midterm  homework  final  report
202311111       80        25     75      35
202344444       75        23     80      27


In [46]:
# 7-5
# loc을 사용하여 indexing과 slicing : 값 읽기, 바꾸기
print(df_course.loc[:, 'midterm']) # Series

202311111    80
202322222    70
202333333    65
202344444    75
Name: midterm, dtype: int64


In [47]:
# 7-6
# loc을 사용하여 indexing과 slicing : 값 읽기, 바꾸기
print(df_course.loc['202311111':'202333333', 'midterm':'final'])  # DataFrame

           midterm  homework  final
202311111       80        25     75
202322222       70        20     80
202333333       65        27     70


In [48]:
# 7-7
# loc을 사용하여 indexing과 slicing : 값 읽기, 바꾸기
print(df_course.loc['202311111':'202333333':2, ['midterm','final']])

           midterm  final
202311111       80     75
202333333       65     70


In [49]:
# 7-8
# loc을 사용하여 indexing과 slicing : 값 읽기, 바꾸기
print(df_course.loc['202311111':'202311111', ['midterm']]) # dataframe

           midterm
202311111       80


In [50]:
# 7-9
# loc을 사용하여 indexing과 slicing : 값 읽기, 바꾸기
print(df_course.loc['202311111':'202311111', 'midterm']) # series

202311111    80
Name: midterm, dtype: int64


In [51]:
# 7-10
# loc을 사용하여 indexing과 slicing : 값 읽기, 바꾸기
print(df_course.loc['202311111', 'midterm']) # integer

80


In [52]:
# 7-11
# loc을 사용하여 indexing과 slicing : 값 읽기, 바꾸기
# 일부 행, 일부 열 읽기 (행 목록, 열 목록)
print(df_course.loc[['202311111','202333333'], ['midterm','final']])

           midterm  final
202311111       80     75
202333333       65     70


In [53]:
# 7-12
# loc을 사용하여 indexing과 slicing : 값 읽기, 바꾸기
# 특정 행의 값을 한꺼번에 바꾸기
df_course.loc['202333333'] = 90

In [54]:
# 7-13
# loc을 사용하여 indexing과 slicing : 값 읽기, 바꾸기
# 특정 행, 렬의 값을 바꾸기
df_course.loc['202311111', 'report'] = 90

In [55]:
# 7-14
# loc을 사용하여 indexing과 slicing : 값 읽기, 바꾸기
# 새로운 행 추가하기, 하나의 값으로 설정하거나, 열의 개수와 동일한 개수의 값 준비
df_course.loc['202355555'] = (80, 30, 75, 90)

In [56]:
# 7-15
# loc을 사용하여 indexing과 slicing : 값 읽기, 바꾸기
# 새로운 열을 만들고 동일한 값으로 설정하기
df_course.loc[:,'university'] = 'Ajou'

In [57]:
# 7-16
# loc을 사용하여 indexing과 slicing : 값 읽기, 바꾸기
# 기존 열의 값들을 사용해서 새로운 열의 값으로 설정하기
df_course.loc[:,'exam'] = df_course.loc[:,'midterm'] *0.5 +\
 df_course.loc[:,'final']*0.5

In [58]:
# 8
# iloc을 사용하여 indexing과 slicing : 값 읽기, 바꾸기
#
# df.iloc[index, column]
# df.iloc[index]
# df.iloc[index][column]
# df.iloc[index1:index2:step, column1:column2:step]
# df.iloc[index list][column list]

base_info={'midterm':[80, 70, 65, 75], 'homework':[25, 20, 27, 23],
          'final':[75, 80, 70, 80], 'report':[35, 30, 32, 27]}
index_list=['202311111', '202322222', '202333333', '202344444']
df_course=pd.DataFrame(base_info, index=index_list)

In [59]:
# 8-1
# iloc을 사용하여 indexing과 slicing : 값 읽기, 바꾸기
# 특정 행,열의 값 읽기
print(df_course.iloc[2, 1])

27


In [60]:
# 8-2
# iloc을 사용하여 indexing과 slicing : 값 읽기, 바꾸기
# 행 읽기
print(df_course.iloc[2]) # series

midterm     65
homework    27
final       70
report      32
Name: 202333333, dtype: int64


In [61]:
# 8-3
# iloc을 사용하여 indexing과 slicing : 값 읽기, 바꾸기
# column 읽기
print(df_course.iloc[:, 0]) # series

202311111    80
202322222    70
202333333    65
202344444    75
Name: midterm, dtype: int64


In [62]:
# 8-4
# iloc을 사용하여 indexing과 slicing : 값 읽기, 바꾸기
# 일부 행, 일부 열 읽기 (행 구간, 열 구간), 구간의 ending index 미포함
print(df_course.iloc[0:2, 0:2])

           midterm  homework
202311111       80        25
202322222       70        20


In [63]:
# 8-5
# iloc을 사용하여 indexing과 slicing : 값 읽기, 바꾸기
# 일부 행, 일부 열 읽기 (행 구간, 열 목록), 구간의 ending index 미포함
print(df_course.iloc[0:2:2, [0, 1]])

           midterm  homework
202311111       80        25


In [64]:
# 8-6
# iloc을 사용하여 indexing과 slicing : 값 읽기, 바꾸기
# 일부 행, 일부 열 읽기 (행 목록, 열 목록)
print(df_course.iloc[[0,2], [0, 2]])

           midterm  final
202311111       80     75
202333333       65     70


In [65]:
# 8-7
# iloc을 사용하여 indexing과 slicing : 값 읽기, 바꾸기
# 특정 열의 값을 한꺼번에 바꾸기
df_course.iloc[:, 1] = 90

In [66]:
# 8-8
# iloc을 사용하여 indexing과 slicing : 값 읽기, 바꾸기
# 기존 열의 값들을 사용해서 새로운 열의 값으로 설정하기
df_course['exam'] = 0 # 새로운 열을 만들고 0으로 초기화
df_course.iloc[:, 4] = df_course.iloc[:, 0] *0.5 + df_course.iloc[:, 3]*0.5

In [67]:
# 9
# at, iat을 사용해서 indexing: 값 읽기, 바꾸기
# slicing은 불가

base_info={'midterm':[80, 70, 65, 75], 'homework':[25, 20, 27, 23],
          'final', :[75, 80, 70, 80], 'report':[35, 30, 32, 27]}
index_list=['202311111', '202322222', '202333333', '202344444']
cols = ['midterm','homework','final',  'report']
df_course=pd.DataFrame(base_info, index=index_list)

SyntaxError: ':' expected after dictionary key (2971890609.py, line 6)

In [68]:
# 9-1
# at, iat을 사용해서 indexing: 값 읽기, 바꾸기
df_course.at['202311111', 'midterm'] = 90
print(df_course.at['202311111', 'midterm'])

90


In [69]:
# 9-2
# at, iat을 사용해서 indexing: 값 읽기, 바꾸기
df_course.iat[1, 2] = 70
print(df_course.iat[1, 2])

70


#### DataFrame 모양 변경

In [70]:
# 10-1
data = {'name': ['Alice', 'Bob', 'Charlie'], 'age': [25, 30, 35]}
df = pd.DataFrame(data, index=['lastborn', 'younger1', 'older1'])
print('*** initial frame\n', df)

# 새로운 행 추가를 위한 DataFrame 생성
new_row_df = pd.DataFrame(data ={'name': 'David', 'age': 28}, 
                          index=['younger2'])
print('\n*** a DataFrame for a new row\n', new_row_df)

# DataFrame 붙이기
df = pd.concat([df, new_row_df])
print('\n*** add a new row\n', df)

*** initial frame
              name  age
lastborn    Alice   25
younger1      Bob   30
older1    Charlie   35

*** a DataFrame for a new row
            name  age
younger2  David   28

*** add a new row
              name  age
lastborn    Alice   25
younger1      Bob   30
older1    Charlie   35
younger2    David   28


In [71]:
# 10-2
# column 별로 수집된 data로 DataFrame을 만들어서 추가하기
new_data = {'name': ['Eva', 'Frank'], 'age': [29, 22], 'sexuality': ['female', 'male']}
new_df = pd.DataFrame(new_data, index=['younger3', 'younger4'])
print('\n*** new data frame\n', new_df)

df = pd.concat([df, new_df]);
print('\n*** attach new data frame\n', df)


*** new data frame
            name  age sexuality
younger3    Eva   29    female
younger4  Frank   22      male

*** attach new data frame
              name  age sexuality
lastborn    Alice   25       NaN
younger1      Bob   30       NaN
older1    Charlie   35       NaN
younger2    David   28       NaN
younger3      Eva   29    female
younger4    Frank   22      male


In [72]:
# 10-3
# 특정 값을 바꾸기, 변경 전 : 변경 후 dictionary 형식으로 argument 제공
df=df.replace({22:23, 25:26})
print('\n*** change value (22->23, 25->26)\n', df)


*** change value (22->23, 25->26)
              name  age sexuality
lastborn    Alice   26       NaN
younger1      Bob   30       NaN
older1    Charlie   35       NaN
younger2    David   28       NaN
younger3      Eva   29    female
younger4    Frank   23      male


In [73]:
# 10-4
# 'city' 열 추가하기 (각 행의 값들을 제시)
df['city'] = ['seoul','busan','suwon', 'suwon', 'suwon', 'pangyo']
print('\n*** add a new column "city"\n', df)


*** add a new column "city"
              name  age sexuality    city
lastborn    Alice   26       NaN   seoul
younger1      Bob   30       NaN   busan
older1    Charlie   35       NaN   suwon
younger2    David   28       NaN   suwon
younger3      Eva   29    female   suwon
younger4    Frank   23      male  pangyo


In [74]:
# 10-5
df = df.drop(columns=['sexuality'], axis=1)
print('\n*** drop sexuality\n', df)


*** drop sexuality
              name  age    city
lastborn    Alice   26   seoul
younger1      Bob   30   busan
older1    Charlie   35   suwon
younger2    David   28   suwon
younger3      Eva   29   suwon
younger4    Frank   23  pangyo


In [3]:
# 10-6
df = df.drop(index=['younger3', 'younger4'])
print('\n*** drop two members\n', df) 

NameError: name 'df' is not defined

In [ ]:
# 10-7
df = df.sort_values(by=['age'], ascending=[False])
print('\n*** sort by "age"\n', df)

In [2]:
# 10-8
for idx, name, age, city in zip(df.index, df['name'], 
                                  df['age'], df['city']):
    print(f"{idx:<8s}:  Name={name:>7s}, Age={age}, Residence={city}")

NameError: name 'df' is not defined

In [78]:
# 11
# dataframe 내 column간 연산해서 새로운 column 만들기

# Apple과 Microsoft와 Google의 현재 주가는 각각 $150, $200, $1200이라고 가정하자.
# Apple과 Microsoft와 Google의 주식을 각각 10주, 5주, 2주를 갖고 있다고 하자.
# Pandas를 사용해서 내 주식 자산 가치를 관리하고 싶다 

import pandas as pd

# 데이터 준비
data = {
    'Price': [150, 200, 1200],
    'Holdings': [10, 5, 2]
}

stocks = ['AAPL', 'MSFT', 'GOOGL']

# DataFrame 생성 및 인덱스 설정
stock_df = pd.DataFrame(data, index=stocks)
stock_df.index.name = 'Stock'

# 각 종목의 자산 가치 계산해서 column으로 추가
stock_df['Asset Value'] = stock_df['Price'] * stock_df['Holdings']

# 총 자산 가치 계산
total_asset_value = stock_df['Asset Value'].sum()

print("포트폴리오 자산 가치:")
print(stock_df)
print("\n총 자산 가치: $", total_asset_value)

포트폴리오 자산 가치:
       Price  Holdings  Asset Value
Stock                              
AAPL     150        10         1500
MSFT     200         5         1000
GOOGL   1200         2         2400

총 자산 가치: $ 4900


#### data frame operation

In [79]:
# 12-1
df1 = pd.DataFrame(data= [[1, 2, 3], [4, 5, 6], [7, 8, 9]], 
                  index= ['spring', 'summer', 'winter'], 
                  columns=['sun', 'mon', 'tue'])

add_by_2 = df1 + 2
print(add_by_2); 

        sun  mon  tue
spring    3    4    5
summer    6    7    8
winter    9   10   11


In [80]:
# 12-2
mult_by_2 = df1 * 2
print(mult_by_2); 

        sun  mon  tue
spring    2    4    6
summer    8   10   12
winter   14   16   18


In [81]:
# 12-3
not_equal_2 = (df1 != 2)
print(not_equal_2)

         sun    mon   tue
spring  True  False  True
summer  True   True  True
winter  True   True  True


In [82]:
# 13-1
df2 = pd.DataFrame(data = [[4, 3, 2], [2, 3, 6], [1, 3, 2]], 
                  index = ['spring', 'summer', 'winter'], 
                  columns = ['sun', 'mon', 'tue'])

sum_dfs = df1 + df2 
print(sum_dfs)

        sun  mon  tue
spring    5    5    5
summer    6    8   12
winter    8   11   11


In [83]:
# 13-2
compare_dfs = (df1 < df2)
print(compare_dfs)

          sun    mon    tue
spring   True   True  False
summer  False  False  False
winter  False  False  False


In [84]:
# 14
import pandas as pd
df1 = pd.DataFrame(data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]], 
                  index = ['spring', 'summer', 'winter'], 
                  columns = ['sun', 'mon', 'tue'])

df2 = pd.DataFrame(data = [[4, 3, 2], [2, 3, 6], [1, 3, 2]], 
                  index = ['spring', 'early summer', 'winter'], 
                  columns = ['sun', 'mon', 'wed'])

print(df2)

sum_dfs = df1 + df2
print(sum_dfs)
print("-"*5)

# sum_dfs의 NaN을 0으로 채우기
sum_dfs = sum_dfs.fillna(0)
print(sum_dfs);

              sun  mon  wed
spring          4    3    2
early summer    2    3    6
winter          1    3    2
               mon  sun  tue  wed
early summer   NaN  NaN  NaN  NaN
spring         5.0  5.0  NaN  NaN
summer         NaN  NaN  NaN  NaN
winter        11.0  8.0  NaN  NaN
-----
               mon  sun  tue  wed
early summer   0.0  0.0  0.0  0.0
spring         5.0  5.0  0.0  0.0
summer         0.0  0.0  0.0  0.0
winter        11.0  8.0  0.0  0.0


In [85]:
# 15
# boolean indexing
df1 = pd.DataFrame(data= [[1, 2, 3], [4, 5, 6], [7, 8, 9]], 
                  index= ['spring', 'summer', 'winter'], 
                  columns=['sun', 'mon', 'tue'])

print(df1[df1['sun'] != 3])

        sun  mon  tue
spring    1    2    3
summer    4    5    6
winter    7    8    9


In [86]:
# 16
# boolean indexing

populations = [['한국',500],['미국', 450],['싱가폴', 705], ['호주', 878], ['베트남', 660], ['대만', 808]]

df = pd.DataFrame(populations, columns = ['country', 'population'])

In [87]:
# 16-1
# boolean indexing
# 한국과 호주 data만 추출
korea_au=df[(df['country']=='한국') | (df['country']=='호주')]
print(korea_au)

  country  population
0      한국         500
3      호주         878


In [88]:
# 16-2
# boolean indexing
# population이 500보다 큰 나라명 출력
big_countries = list(df[df['population']>500]['country'])
print (big_countries) 

['싱가폴', '호주', '베트남', '대만']


In [89]:
# 16-3
# boolean indexing
# loc을 사용한 boolean indexing
# 인구가 500 이상인 행 출력
print(df.loc[df['population'] >= 500]) # print(df[df['population'] >= 500]) 

  country  population
0      한국         500
2     싱가폴         705
3      호주         878
4     베트남         660
5      대만         808


In [90]:
# 16-4
# boolean indexing
# ‘size’라는 열을 추가하고, 인구가 500이상이면 ‘big’, 그렇지 않으면 ‘small’ 값 부여
df.loc[df['population'] >= 500, 'size'] = 'big'  
df.loc[df['population'] < 500, 'size'] = 'small'  

print(df)

  country  population   size
0      한국         500    big
1      미국         450  small
2     싱가폴         705    big
3      호주         878    big
4     베트남         660    big
5      대만         808    big


/tmp/ipykernel_1190/2557146637.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'big' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df['population'] >= 500, 'size'] = 'big'


In [91]:
# 17 
# iloc을 사용한 boolean indexing

data = {'items': ['apple', 'peach', 'pear', 'orange', 'strawberry'],
'sales': [100, 130, 250, 210, 200]}
df = pd.DataFrame(data)
print(df)

        items  sales
0       apple    100
1       peach    130
2        pear    250
3      orange    210
4  strawberry    200


In [92]:
# 17-1
# iloc을 사용한 boolean indexing
# 'state'라는 열을 추가하고 default로 'good' 부여
df['state'] = 'good'   
print(df)

        items  sales state
0       apple    100  good
1       peach    130  good
2        pear    250  good
3      orange    210  good
4  strawberry    200  good


In [93]:
# 17-2 
# iloc을 사용한 boolean indexing
# sales가 150 미만인 항목에 대해서는 RangeIndex가 2인 column, 즉, state를 'bad'로 변경
df.iloc[df['sales'] <150, 2] = 'bad' 
print(df)

        items  sales state
0       apple    100   bad
1       peach    130   bad
2        pear    250  good
3      orange    210  good
4  strawberry    200  good


In [94]:
# 18 
# data frame 내 특정 값이 어디에 있는지 찾기
import numpy as np

# 기본 data
fruits = ['apple', 'peach', 'pear', 'orange', 'strawberry']
coffee = ['americano', 'latte', 'americano', 'capuccino', 'latte']
color = ['green', 'blue', 'pink', 'red', 'blue']
user_list = ['kang', 'kim', 'lee', 'hong', 'cho']

# data frame을 만들기 위한 준비
categories = ['fruits', 'coffee', 'color']
items_list = [fruits, coffee, color]
favorites = {categories[i]: items_list[i] for i in range(len(categories))}
print(favorites)

print("*"*10)
df = pd.DataFrame(favorites, index = user_list )
print(df)

{'fruits': ['apple', 'peach', 'pear', 'orange', 'strawberry'], 'coffee': ['americano', 'latte', 'americano', 'capuccino', 'latte'], 'color': ['green', 'blue', 'pink', 'red', 'blue']}
**********
          fruits     coffee  color
kang       apple  americano  green
kim        peach      latte   blue
lee         pear  americano   pink
hong      orange  capuccino    red
cho   strawberry      latte   blue


In [95]:
# 18-1
# data frame 내 특정 값이 어디에 있는지 찾기
target = 'americano'

record_df = df[df.isin([target]).any(axis=1)]
print(record_df.index.tolist())  

['kang', 'lee']


In [96]:
# 18-2
# data frame 내 특정 값이 어디에 있는지 찾기
target = 'americano'
target_column = 'coffee'

record_df = df[df[target_column] == target]
print(record_df.index.tolist())

['kang', 'lee']


In [97]:
# 18-3
# data frame 내 특정 값이 어디에 있는지 찾기
target = 'americano'
target_column = 'coffee'

record_df = df.loc[df[target_column] == target]
print(record_df.index.tolist())

['kang', 'lee']


In [98]:
# 18-4
# data frame 내 특정 값이 어디에 있는지 찾기
target = 'americano'
target_column = 'coffee'
record_df = df[df[target_column].str.contains(target)]
print(record_df.index.tolist())

['kang', 'lee']


In [99]:
# 18-5 
# data frame 내 특정 값이 어디에 있는지 찾기
target = 'americano'
target_column = 'coffee'
record_df = df.query(f"{target_column} == '{target}'")
print(record_df.index.tolist())

['kang', 'lee']


In [100]:
# 19
# data frame 내 특정 값이 어디에 있는지 찾기의 상세 과정 확인
# 5명에 대해 과일, 커피, 색깔 선호도 조사 결과
data = {'fruits': ['apple', 'peach', 'pear', 'orange', 'strawberry'], 
        'coffee': ['americano', 'latte', 'americano', 'capuccino', 'latte'], 
        'color': ['green', 'blue', 'pink', 'red', 'blue']}
user_list = ['kang', 'kim', 'lee', 'hong', 'cho']
df = pd.DataFrame(data, index=user_list)
print(df)

# favorite item이 target에 하나라도 속하는 사람 찾기
target = ['americano', 'apple', 'blue']
print("-"*5)

# dataframe 각 element들에 대해 target에 포함되는지 확인
print(df.isin(target))
print("-"*5)

# 열 값 중 하나라도 True인 경우에만 True이 series 생성
print(df.isin(target).any(axis=1))
print("-"*5)

# 열 값 중 하나라도 True인 행만 추출
print(df[df.isin(target).any(axis=1)])
print("-"*5)

# 열 값 중 하나라도 True인 행의 index label을 추출해서 list로 변환
print(list(df[df.isin(target).any(axis=1)].index))

          fruits     coffee  color
kang       apple  americano  green
kim        peach      latte   blue
lee         pear  americano   pink
hong      orange  capuccino    red
cho   strawberry      latte   blue
-----
      fruits  coffee  color
kang    True    True  False
kim    False   False   True
lee    False    True  False
hong   False   False  False
cho    False   False   True
-----
kang     True
kim      True
lee      True
hong    False
cho      True
dtype: bool
-----
          fruits     coffee  color
kang       apple  americano  green
kim        peach      latte   blue
lee         pear  americano   pink
cho   strawberry      latte   blue
-----
['kang', 'kim', 'lee', 'cho']


In [101]:
# 20
# group별로 데이터 나누기
data = {'Category': ['A', 'B', 'A', 'B', 'A', 'B'],
'Value': [10, 15, 20, 25, 30, 35]}
df = pd.DataFrame(data)

In [102]:
# 20-1
# group별로 데이터 나누기
grouped = df.groupby(['Category'])  
print(grouped.groups.keys())  
print(df.index)

dict_keys(['A', 'B'])
RangeIndex(start=0, stop=6, step=1)


In [103]:
# 20-2
# group별로 데이터 나누기
A_df=grouped.get_group('A')  
print(A_df)
print(A_df.index)
print(A_df.columns)

  Category  Value
0        A     10
2        A     20
4        A     30
Index([0, 2, 4], dtype='int64')
Index(['Category', 'Value'], dtype='object')


In [104]:
# 20-3
# group별로 데이터 나누기
group_mean_df = grouped.mean() 
print(group_mean_df)
print(group_mean_df.index)
print(group_mean_df.columns)

          Value
Category       
A          20.0
B          25.0
Index(['A', 'B'], dtype='object', name='Category')
Index(['Value'], dtype='object')


In [105]:
# 20-4
# group별로 데이터 나누기
group_count_df = grouped.count()  
print(group_count_df)
print(group_count_df.index)
print(group_count_df.columns)

          Value
Category       
A             3
B             3
Index(['A', 'B'], dtype='object', name='Category')
Index(['Value'], dtype='object')


In [106]:
# 21
# group별로 데이터 나누기, 다중 조건 사용하기

import pandas as pd

data = {'grade': [1, 2, 2, 3, 1, 3, 3], 
        'gender': ['M', 'F', 'M', 'F', 'F', 'M', 'F'], 
        'score': [80, 90, 70, 60, 85, 95, 75]}
df = pd.DataFrame(data)

# 학년로, 동일 학년에서는 성별로 그룹
grouped = df.groupby(['grade', 'gender'])
result = grouped['score'].agg(['mean', 'min', 'max', 'count'])
print(result)

# 성별로, 동일 성별에서는 학년별로 그룹
grouped = df.groupby(['gender', 'grade']) 
result = grouped['score'].agg(['mean', 'min', 'max', 'count'])
print(result)

              mean  min  max  count
grade gender                       
1     F       85.0   85   85      1
      M       80.0   80   80      1
2     F       90.0   90   90      1
      M       70.0   70   70      1
3     F       67.5   60   75      2
      M       95.0   95   95      1
              mean  min  max  count
gender grade                       
F      1      85.0   85   85      1
       2      90.0   90   90      1
       3      67.5   60   75      2
M      1      80.0   80   80      1
       2      70.0   70   70      1
       3      95.0   95   95      1


### 데이터 구조 비교

In [107]:
# 22
# dictionary, numpy array, pandas series, pandas dataframe 비교
# 생성 절차 비교
scores = [[80, 25, 75, 35], [70, 20, 80, 30], [65, 27, 70, 32], [75, 23, 80, 27]]
students = ['202311111', '202322222', '202333333', '202344444']
metrics = ['중간고사', '과제', '기말고사', '보고서']

score_dict = {students[i]:{metrics[j]:scores[i][j] for j in range(len(metrics))} 
              for i in range(len(students))}
print(score_dict)

import numpy as np
score_array = np.array(scores)
print(score_array)

import pandas as pd
score_series =[pd.Series(score, index=metrics, name=students[i]) 
               for i, score in enumerate(scores)]
print(score_series)

score_df = pd.DataFrame(scores, index=students, columns=metrics)
print(score_df)

{'202311111': {'중간고사': 80, '과제': 25, '기말고사': 75, '보고서': 35}, '202322222': {'중간고사': 70, '과제': 20, '기말고사': 80, '보고서': 30}, '202333333': {'중간고사': 65, '과제': 27, '기말고사': 70, '보고서': 32}, '202344444': {'중간고사': 75, '과제': 23, '기말고사': 80, '보고서': 27}}
[[80 25 75 35]
 [70 20 80 30]
 [65 27 70 32]
 [75 23 80 27]]
[중간고사    80
과제      25
기말고사    75
보고서     35
Name: 202311111, dtype: int64, 중간고사    70
과제      20
기말고사    80
보고서     30
Name: 202322222, dtype: int64, 중간고사    65
과제      27
기말고사    70
보고서     32
Name: 202333333, dtype: int64, 중간고사    75
과제      23
기말고사    80
보고서     27
Name: 202344444, dtype: int64]
           중간고사  과제  기말고사  보고서
202311111    80  25    75   35
202322222    70  20    80   30
202333333    65  27    70   32
202344444    75  23    80   27


In [108]:
# 23
# dictionary, numpy array, pandas series, pandas dataframe 비교
# '202322222'의 '과제' 점수를 70으로 변경

# Dictionary 업데이트
score_dict['202322222']['과제'] = 70
print("\nUpdated Dictionary:")
print(score_dict)

# Numpy Array 업데이트
score_array[students.index('202322222'), metrics.index('과제')] = 70
print("\nUpdated array:")
print(score_array)

# Pandas Series 업데이트
for series in score_series:
    if series.name == '202322222':
        series['과제'] = 70
print("\nUpdated series:")
print(score_series)

# Pandas dataframe update
score_df.at['202322222', '과제'] = 70
print("\nUpdated dataframe:")
print(score_df)


Updated Dictionary:
{'202311111': {'중간고사': 80, '과제': 25, '기말고사': 75, '보고서': 35}, '202322222': {'중간고사': 70, '과제': 70, '기말고사': 80, '보고서': 30}, '202333333': {'중간고사': 65, '과제': 27, '기말고사': 70, '보고서': 32}, '202344444': {'중간고사': 75, '과제': 23, '기말고사': 80, '보고서': 27}}

Updated array:
[[80 25 75 35]
 [70 70 80 30]
 [65 27 70 32]
 [75 23 80 27]]

Updated series:
[중간고사    80
과제      25
기말고사    75
보고서     35
Name: 202311111, dtype: int64, 중간고사    70
과제      70
기말고사    80
보고서     30
Name: 202322222, dtype: int64, 중간고사    65
과제      27
기말고사    70
보고서     32
Name: 202333333, dtype: int64, 중간고사    75
과제      23
기말고사    80
보고서     27
Name: 202344444, dtype: int64]

Updated dataframe:
           중간고사  과제  기말고사  보고서
202311111    80  25    75   35
202322222    70  70    80   30
202333333    65  27    70   32
202344444    75  23    80   27


In [109]:
# 24
# dictionary, numpy array, pandas series, pandas dataframe 비교
# 총점 계산 (비율 적용)

weights = {'중간고사': 0.3, '과제': 0.2, '기말고사': 0.3, '보고서': 0.2}

# Dictionary 업데이트 (총점 추가)
for student in students:
    total_score = sum(score_dict[student][metric] * weights[metric] 
                        for metric in metrics)
    score_dict[student]['총점'] = total_score
print("\nUpdated Dictionary with '총점':")
print(score_dict)

# Numpy Array 업데이트 (총점 추가)
total_scores = np.array([sum(row[j] * weights[metrics[j]] 
                           for j in range(len(metrics))) 
                               for row in score_array])
new_score_array = np.hstack((score_array, total_scores.reshape(-1, 1)))

print("\nUpdated Numpy Array with '총점':")
print(new_score_array)

# Pandas Series 업데이트 (총점 추가)
for series in score_series:
    total_score = sum(series[metric] * weights[metric] for metric in metrics)
    series['총점'] = total_score

print("\nUpdated Pandas Series with '총점':")
for series in score_series:
    print(series)

# Pandas dataframe 업데이트 (총점 추가)
score_df['총점'] = score_df.apply(lambda row: sum(row[metric] * weight 
                                                for metric, weight in 
                                                     weights.items()), axis=1)

print("\nDataFrame with '총점':")
print(score_df)


Updated Dictionary with '총점':
{'202311111': {'중간고사': 80, '과제': 25, '기말고사': 75, '보고서': 35, '총점': 58.5}, '202322222': {'중간고사': 70, '과제': 70, '기말고사': 80, '보고서': 30, '총점': 65.0}, '202333333': {'중간고사': 65, '과제': 27, '기말고사': 70, '보고서': 32, '총점': 52.3}, '202344444': {'중간고사': 75, '과제': 23, '기말고사': 80, '보고서': 27, '총점': 56.5}}

Updated Numpy Array with '총점':
[[80.  25.  75.  35.  58.5]
 [70.  70.  80.  30.  65. ]
 [65.  27.  70.  32.  52.3]
 [75.  23.  80.  27.  56.5]]

Updated Pandas Series with '총점':
중간고사    80.0
과제      25.0
기말고사    75.0
보고서     35.0
총점      58.5
Name: 202311111, dtype: float64
중간고사    70.0
과제      70.0
기말고사    80.0
보고서     30.0
총점      65.0
Name: 202322222, dtype: float64
중간고사    65.0
과제      27.0
기말고사    70.0
보고서     32.0
총점      52.3
Name: 202333333, dtype: float64
중간고사    75.0
과제      23.0
기말고사    80.0
보고서     27.0
총점      56.5
Name: 202344444, dtype: float64

DataFrame with '총점':
           중간고사  과제  기말고사  보고서    총점
202311111    80  25    75   35  58.5
202322222    70  

In [110]:
# 25
# dictionary, numpy array, pandas series, pandas dataframe 비교
# '과제' 점수가 90점 이상인 학생들에게 '마일리지' 10 부여

threshold, points, default = 25, 10, 0

# Dictionary 업데이트
for student in students:
    if score_dict[student]['과제'] >= threshold:
        score_dict[student]['마일리지'] = points
    else:
        score_dict[student]['마일리지'] = default
print(score_dict)
        
# Numpy Array 업데이트
new_score_array = np.hstack((score_array, 
                             np.zeros((score_array.shape[0], 1), dtype=int)))
for i, student in enumerate(students):
    if score_array[i, metrics.index('과제')] >= threshold:
        new_score_array[i, -1] = points 
print(new_score_array)

# pandas series 업데이트
for series in score_series:
    series['마일리지'] = default
    if series['과제'] >= threshold:
        series['마일리지'] = points 
print(score_series)

# data frame에  '마일리지' 열을 추가하고 기본 값을 0으로 설정
score_df['마일리지'] = default
score_df.loc[score_df['과제'] >= threshold, '마일리지'] = points 
print(score_df)

{'202311111': {'중간고사': 80, '과제': 25, '기말고사': 75, '보고서': 35, '총점': 58.5, '마일리지': 10}, '202322222': {'중간고사': 70, '과제': 70, '기말고사': 80, '보고서': 30, '총점': 65.0, '마일리지': 10}, '202333333': {'중간고사': 65, '과제': 27, '기말고사': 70, '보고서': 32, '총점': 52.3, '마일리지': 10}, '202344444': {'중간고사': 75, '과제': 23, '기말고사': 80, '보고서': 27, '총점': 56.5, '마일리지': 0}}
[[80 25 75 35 10]
 [70 70 80 30 10]
 [65 27 70 32 10]
 [75 23 80 27  0]]
[중간고사    80.0
과제      25.0
기말고사    75.0
보고서     35.0
총점      58.5
마일리지    10.0
Name: 202311111, dtype: float64, 중간고사    70.0
과제      70.0
기말고사    80.0
보고서     30.0
총점      65.0
마일리지    10.0
Name: 202322222, dtype: float64, 중간고사    65.0
과제      27.0
기말고사    70.0
보고서     32.0
총점      52.3
마일리지    10.0
Name: 202333333, dtype: float64, 중간고사    75.0
과제      23.0
기말고사    80.0
보고서     27.0
총점      56.5
마일리지     0.0
Name: 202344444, dtype: float64]
           중간고사  과제  기말고사  보고서    총점  마일리지
202311111    80  25    75   35  58.5    10
202322222    70  70    80   30  65.0    10
202333333    65  

In [111]:
### data 분석 연습
import pandas as pd
import numpy as np

item_list = ['Americano', 'Latte', 'Tea', 'Juice', 'Cake']  # 품목명
user_list = ['Irene', 'Edith', 'Gaby', 'Anna', 'Erica', 'Charles', 'Bailey']  
# 고객 이름

user_purchase={}
for item in item_list: # 각 품목의 구매액을 10,000~30,000 사이로 고객 수 만큼 생성
    user_purchase[item] = np.random.randint(10, 31, len(user_list)) * 1000
df = pd.DataFrame(user_purchase, index=user_list)  # data frame 생성
print(df)

         Americano  Latte    Tea  Juice   Cake
Irene        23000  12000  29000  26000  19000
Edith        23000  22000  19000  20000  28000
Gaby         24000  10000  10000  25000  19000
Anna         28000  26000  13000  25000  22000
Erica        30000  26000  26000  11000  14000
Charles      15000  20000  18000  29000  26000
Bailey       25000  11000  20000  29000  24000


In [ ]:
# P1
# 위에서 정의된 dataframe을 사용하여 문제를 푸시오
# Console로 고객 이름과 품목 이름을 한 번에 입력 받아서 그 고객의 품목 구매액 출력하라 
# 등록되지 않은 고객 이름이거나 품목 이름 입력 시 오류 메시지 출력
#
# 실행 사례1)
# 고객 이름과 품목 입력: Edith Latte
# ----------
# Edith Latte 16000
#
# 실행 사례2)
# 고객 이름과 품목 입력: Gaby Cocoa
# 품목명 Cocoa 오류
#
# 실행 사례3)
# 고객 이름과 품목 입력: Kang Cocoa
# 고객명 Kang 오류     품목명 Cocoa 오류

user, item=input("고객 이름과 품목 입력:").split()
if user in user_list and item in item_list:
    purchase=df.loc[user, item]
    print("-"*10)
    print(user, item, purchase)
else:
    if user not in user_list:
        print(f"고객명 {user} 오류", end=" ")
    if item not in item_list:
        print(f"품목명 {item} 오류")

In [ ]:
# P2
# Console로 고객들 이름을 입력 받고, 품목 이름들을 입력 받아서, 
# 고객들의 품목별 구매액을 data frame으로 출력하라 
# 
# 고객명이나 품목명에 오류가 있을 시 오류 메시지를 출력하시오 
# 일부만 잘못된 입력의 경우, 정상적인 고객명과 품목명에 대해서 data frame으로 출력
#
# 실행 사례1)
# 고객들 이름 입력: Erica Charles 
# 품목 목록 입력: Latte Tea
# ----------
#         Latte    Tea
# Erica    20000  11000
# Charles  15000  21000
#
# 실행 사례2)
# 고객들 이름 입력: Erica Kang
# 품목 목록 입력: Tea Cocoa
# ----------
#         Tea
# Erica  11000
# 고객명 ['Kang'] 오류
# 품목명 ['Cocoa'] 오류

users = input("고객들 이름 입력:").split()
items = input("품목 목록 입력:").split()

print("-"*10)

user_errors = [user for user in users if user not in user_list]
item_errors = [item for item in items if item not in item_list]

user_valid = [user for user in users if user in user_list]
item_valid = [item for item in items if item in item_list]

if user_valid and item_valid:
    wanted=df.loc[user_valid, item_valid]
    print(wanted)

if user_errors:
    print(f"고객명 {user_errors} 오류")

if product_errors:
    print(f"품목명 {item_errors} 오류")

In [ ]:
# P3
# Console로 품목명과 차액을 입력받아서 해당 항목의 값을 모두 바꾸고, 
# 변경 전과 변경 후를 출력하시오
# 입력 사례는, Latte -1000 , Latte +1000. 
# 등록되지 않은 품목 이름 입력 시 오류 메시지 출력
# 실행 사례)
# 품목 목록: ['Americano', 'Latte', 'Tea', 'Juice', 'Cake']
# 품목명 차액 입력(예: Latte -1000): Juice -1000
# 변경 전 Juice ----------
# Irene      21000
# Edith      14000
# Gaby       24000
# Anna       14000
# Erica      17000
# Charles    21000
# Bailey     29000
# Name: Juice, dtype: int64
# 변경 후 Juice ----------
# Irene      20000
# Edith      13000
# Gaby       23000
# Anna       13000
# Erica      16000
# Charles    20000
# Bailey     28000
# Name: Juice, dtype: int64

print("품목 목록:", item_list)
input_list=input("품목명과 차액 입력(예: Latte -1000):").split()
product, change_val = input_list 
if product in item_list:
    print("변경 전", product, "-"*10)
    print(df[product])
    df[product]+=int(change_val)
    print("변경 후",product, "-"*10)
    print(df[product])
else:
    print(f"품목명 {product} 오류")


In [ ]:
# P4
# 각 품목별 평균 구매액을 계산해서 정수로 출력하라 
# 실행 사례)
# * Americano 평균 판매액: 20000원
# * Latte 평균 판매액: 23000원
# * Tea 평균 판매액: 24285원
# * Juice 평균 판매액: 19000원
# * Cake 평균 판매액: 24142원

for item in item_list:
    print(f"* {item} 평균 판매액: {int(df[item].mean())}원")

In [ ]:
# P5
# Console로 품목과 기준금액을 입력 받아서 
# 그 금액 이상 해당 품목을 구매한 고객 이름과 구매액을 구매액 크기 역순으로 
# 출력하라 
# 실행 사례
# 품목과 기준 금액 입력: Latte 15000
# ----------
# Charles    26000
# Anna       24000
# Edith      20000
# Erica      17000
# Bailey     17000
# Name: Latte, dtype: int64

product_threshold=input("품목과 기준 금액 입력:").split()
product = product_threshold[0]; threshold=int(product_threshold[1])
print("-"*10)
if product in item_list:
    df_heavy_user = df[df[product]>=threshold].sort_values(by=product, ascending=False)
    if df_heavy_user.empty:
        print(f"{product}을 {threshold}원 이상 구매한 고객이 없습니다")
    else:
        print(df_heavy_user[product])
else:
    print(f"품목명 {product} 오류")

In [ ]:
# P6
# 기준 금액보다 구매액이 낮은 고객이 3명 이상이면 해당 품목 판매를 중단하고자 한다.  
# 기준 금액을 입력받아서, 판매 중단할 품목이 무엇인지 출력하라 
# 실행 사례1) 
# 기준 금액 입력: 10000
# ----------
# 판매 중단 대상이 없습니다
# 실행 사례2)
# 기준 금액 입력: 20000
# ----------
# 판매 중단 품목은 ['Americano', 'Juice'] 입니다

threshold=int(input("기준 금액 입력:"))
stop_list = []; threshold_count=3
for item in item_list:
    num_below_threshold = (df[item] <= threshold).sum() # True=1, False=0
    if num_below_threshold >= threshold_count:
        stop_list.append(item)
print("-"*10)
if stop_list:
    print("판매 중단 품목은", stop_list, "입니다")
else:
    print("판매 중단 대상이 없습니다")